# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'shipinzp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for shipinzp

  target 'shipinzpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'shipinzpUITests' do
    # Pods for testing
  end
pod 'AFNetworking'

end
